#!/usr/bin/env bash
set -euo pipefail

# updateVersion.sh
# Reads version-*.txt (generated by generateVersion.sh) and updates project files:
# - index.html (${VERSION} placeholder)
# - src-tauri/tauri.conf.json (replace ${VERSION} and "version": "..."
# - android/app/build.gradle (versionName and versionCode)
# - ios/App/App/Info.plist (CFBundleShortVersionString and CFBundleVersion)
# Usage: ./scripts/updateVersion.sh

# Find version file
VERSION_FILE=$(ls version-*.txt 2>/dev/null | head -n1 || true)
if [[ -z "$VERSION_FILE" ]]; then
  echo "No version-*.txt found. Using fallback values." >&2
  VERSION="0.0.2-fallback"
  MAJOR_MINOR_PATCH="0.0.2"
  FULL_SEMVER="0.0.2-fallback"
  GIT_HASH="unknown"
  GIT_TAG="allback"
  GIT_BRANCH="unknown"
  COMMIT_COUNT=0
  BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
else
  echo "Reading version info from $VERSION_FILE"
  # shellcheck disable=SC2002
  VERSION=$(grep '^version=' "$VERSION_FILE" | head -n1 | cut -d'=' -f2-)
  MAJOR_MINOR_PATCH=$(grep '^major_minor_patch=' "$VERSION_FILE" | head -n1 | cut -d'=' -f2-)
  FULL_SEMVER=$(grep '^full_semver=' "$VERSION_FILE" | head -n1 | cut -d'=' -f2-)
  GIT_HASH=$(grep '^git_hash=' "$VERSION_FILE" | head -n1 | cut -d'=' -f2-)
  GIT_TAG=$(grep '^git_tag=' "$VERSION_FILE" | head -n1 | cut -d'=' -f2-)
  GIT_BRANCH=$(grep '^git_branch=' "$VERSION_FILE" | head -n1 | cut -d'=' -f2-)
  COMMIT_COUNT=$(grep '^commit_count=' "$VERSION_FILE" | head -n1 | cut -d'=' -f2-)
  BUILD_DATE=$(grep '^build_date=' "$VERSION_FILE" | head -n1 | cut -d'=' -f2-)
fi

# Fallbacks
VERSION=${VERSION:-"0.0.2-fallback"}
MAJOR_MINOR_PATCH=${MAJOR_MINOR_PATCH:-"0.0.2"}
FULL_SEMVER=${FULL_SEMVER:-"0.0.2-fallback"}
COMMIT_COUNT=${COMMIT_COUNT:-0}

# ensure COMMIT_COUNT is integer
if ! [[ "$COMMIT_COUNT" =~ ^[0-9]+$ ]]; then
  COMMIT_COUNT=0
fi

# Parse MAJOR, MINOR, PATCH from MAJOR_MINOR_PATCH (format: "MAJOR.MINOR.PATCH")
IFS='.' read -r MAJOR MINOR PATCH <<< "$MAJOR_MINOR_PATCH"
MAJOR=${MAJOR:-0}
MINOR=${MINOR:-0}
PATCH=${PATCH:-0}

# Ensure MAJOR, MINOR, PATCH are integers
MAJOR=$((MAJOR + 0))
MINOR=$((MINOR + 0))
PATCH=$((PATCH + 0))

# Compute versionCode: MAJOR * 1000000 + MINOR * 10000 + PATCH * 100 + COMMIT_COUNT
VERSION_CODE=$((MAJOR * 1000000 + MINOR * 10000 + PATCH * 100 + COMMIT_COUNT))

# Export outputs for GitHub Actions if $GITHUB_OUTPUT exists
if [[ -n "${GITHUB_OUTPUT:-}" ]]; then
  {
    echo "VERSION=$VERSION"
    echo "MAJOR_MINOR_PATCH=$MAJOR_MINOR_PATCH"
    echo "FULL_SEMVER=$FULL_SEMVER"
    echo "GIT_HASH=$GIT_HASH"
    echo "GIT_TAG=$GIT_TAG"
    echo "GIT_BRANCH=$GIT_BRANCH"
    echo "COMMIT_COUNT=$COMMIT_COUNT"
    echo "BUILD_DATE=$BUILD_DATE"
  } >> "$GITHUB_OUTPUT"
fi

# Print summary
cat <<EOF
Using version: $VERSION
Major minor patch: $MAJOR_MINOR_PATCH
Full semver: $FULL_SEMVER
Git hash: $GIT_HASH
Git branch: $GIT_BRANCH
Commit count: $COMMIT_COUNT
Build date: $BUILD_DATE
Android versionCode: $VERSION_CODE (MAJOR=$MAJOR MINOR=$MINOR PATCH=$PATCH COMMIT_COUNT=$COMMIT_COUNT)
EOF

# Update package.json only
PACKAGE_JSON="package.json"
if [[ -f "$PACKAGE_JSON" ]]; then
  # Replace the version field in package.json
  perl -0777 -pe "s/\"version\"\s*:\s*\"[^\"]*\"/\"version\": \"$VERSION\"/g" -i "$PACKAGE_JSON"
  echo "Updated $PACKAGE_JSON to version $VERSION"
else
  echo "package.json not found: $PACKAGE_JSON" >&2
fi

echo "Version update complete."
