name: 'Unit Tests'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: current
      - run: npm ci
      - run: npm test
      - name: upload junit
        uses: actions/upload-artifact@v1
        with:
          name: junit
          path: junit.xml
      # displays in summary page
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: 'junit.xml'
      # more in depth junit in console and annotations on failures
      - uses: ashley-taylor/junit-report-annotations-action@1.3
        if: always()
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: junit.xml
      - run: npm run test:coverage
      - name: upload code coverage
        uses: actions/upload-artifact@v1
        with:
          name: Report-CodeCoverage
          path: coverage
      # adds coverage comment to pr
      - name: parse coverage
        uses: danhunsaker/clover-reporter-action@v0.2.17-clover
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          clover-file: ./coverage/clover.xml
